In [1]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta

In [2]:
random.seed(42)
Faker.seed(1000)
fake = Faker()

In [3]:
customer_id = [fake.uuid4() for _ in range(1000)]
name = [fake.name() for _ in range(1000)]
age = [random.randint(18,99) for _ in range(1000)]
state = [fake.state() for _ in range(1000)]

customer_income = ['<30k','30k-60k','60k-90k','90k+']
income_bracket = random.choices(customer_income, k=1000)

credit = ['Poor','Fair','Good','Very Good','Excellent']
w = [0.05,0.15,0.3,0.3,0.2]
credit_score_band = random.choices(credit, weights = w, k=1000)

In [4]:
customers = pd.DataFrame({'customer_id':customer_id,'name':name,'age':age,'state':state,
                          'income_bracket':income_bracket,'credit_score_band':credit_score_band})
customers

,customer_id,name,age,state,income_bracket,credit_score_band
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,Christopher Miller,99,Maine,90k+,Very Good
1,101cd468-5a5c-4689-a4c3-8c4119613698,Jason Nguyen,32,Texas,60k-90k,Excellent
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,Michael Monroe,21,Rhode Island,<30k,Good
3,38c92c57-215c-48da-affe-6666fa72766d,Jennifer Martin,53,Oklahoma,90k+,Good
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,David Snyder,49,Hawaii,30k-60k,Very Good
...,...,...,...,...,...,...
995,baad3a54-d2c2-4533-8116-99f783761819,Michael Gregory,70,Washington,60k-90k,Very Good
996,2ce55216-dd6b-483a-9aec-ce201c8a3085,Stefanie Warren,29,West Virginia,90k+,Very Good
997,a98d00e2-7d55-4459-b168-b9075a8d5640,Melvin Pearson,46,Missouri,60k-90k,Very Good
998,b198002d-13de-4f22-8b81-457e3807a733,Nicole Meza,32,Rhode Island,30k-60k,Good
999,60c78083-2cfc-41c9-b880-cf086c8dfb1c,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good

In [5]:
customers['credit_score_band'].value_counts()

Very Good    315
Good         308
Excellent    191
Fair         141
Poor          45
Name: credit_score_band, dtype: int64

In [6]:
cust_id = []
options = [1,2,3]
weight = [0.80,0.17,0.03]
vals = random.choices(options, weights = weight, k = 1000)

for cus,n in zip(customer_id,vals):
    for i in range(n):
        cust_id.append(cus)

In [7]:
loan = pd.DataFrame({'customer_id':cust_id})

In [8]:
l_id = []

for i in range(1001, len(cust_id)+1001):
    l_id.append(i)
    
len(l_id)
loan_id = ['L' + str(l) for l in l_id]
len(loan_id)

1224

In [9]:
loan = pd.DataFrame({'customer_id':cust_id, 'loan_id':loan_id})
loan

                               customer_id loan_id
0     c2a7af9e-ab79-4005-add1-77d2c700d84c   L1001
1     101cd468-5a5c-4689-a4c3-8c4119613698   L1002
2     fa900d46-88e1-4883-aa6f-30c077c8cd55   L1003
3     38c92c57-215c-48da-affe-6666fa72766d   L1004
4     ade19b1a-5d3e-438b-bd9e-f14dabd69cb9   L1005
...                                    ...     ...
1219  baad3a54-d2c2-4533-8116-99f783761819   L2220
1220  2ce55216-dd6b-483a-9aec-ce201c8a3085   L2221
1221  a98d00e2-7d55-4459-b168-b9075a8d5640   L2222
1222  b198002d-13de-4f22-8b81-457e3807a733   L2223
1223  60c78083-2cfc-41c9-b880-cf086c8dfb1c   L2224

[1224 rows x 2 columns]

In [10]:
band_score = {'Poor':(300,579),'Fair':(580,669),'Good':(670,739),'Very Good':(740,799),'Excellent':(800,850)}

customers['score'] = customers.apply(lambda row: random.randint(band_score[row['credit_score_band']][0],
                                                                band_score[row['credit_score_band']][1]), axis = 1)

customers

,customer_id,name,age,state,income_bracket,credit_score_band,score
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,Christopher Miller,99,Maine,90k+,Very Good,778
1,101cd468-5a5c-4689-a4c3-8c4119613698,Jason Nguyen,32,Texas,60k-90k,Excellent,805
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,Michael Monroe,21,Rhode Island,<30k,Good,706
3,38c92c57-215c-48da-affe-6666fa72766d,Jennifer Martin,53,Oklahoma,90k+,Good,726
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,David Snyder,49,Hawaii,30k-60k,Very Good,764
...,...,...,...,...,...,...,...
995,baad3a54-d2c2-4533-8116-99f783761819,Michael Gregory,70,Washington,60k-90k,Very Good,758
996,2ce55216-dd6b-483a-9aec-ce201c8a3085,Stefanie Warren,29,West Virginia,90k+,Very Good,774
997,a98d00e2-7d55-4459-b168-b9075a8d5640,Melvin Pearson,46,Missouri,60k-90k,Very Good,784
998,b198002d-13de-4f22-8b81-457e3807a733,Nicole Meza,32,Rhode Island,30k-60k,Good,732
999,60c78083-2cfc-41c9-b880-cf086c8dfb1c,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752

In [11]:
customers['score'].describe()

count    1000.000000
mean      725.294000
std        90.403863
min       304.000000
25%       686.000000
50%       741.000000
75%       787.000000
max       850.000000
Name: score, dtype: float64

In [12]:
customers.groupby('credit_score_band')['score'].agg(['min','max'])

                   min  max
credit_score_band
Excellent          800  850
Fair               580  669
Good               670  739
Poor               304  576
Very Good          740  799

In [13]:
def score_grade(row):
    if row['score'] >= 760:
        return 'A'
    elif row['score'] >= 720:
        return 'B'
    elif row['score'] >= 690:
        return 'C'
    elif row['score'] >= 660:
        return 'D'
    elif row['score'] >= 630:
        return 'E'
    elif row['score'] >= 600:
        return 'F'
    else:
        return 'G'

customers['grade'] = customers.apply(score_grade, axis = 1)

customers

,customer_id,name,age,state,income_bracket,credit_score_band,score,grade
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,Christopher Miller,99,Maine,90k+,Very Good,778,A
1,101cd468-5a5c-4689-a4c3-8c4119613698,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,Michael Monroe,21,Rhode Island,<30k,Good,706,C
3,38c92c57-215c-48da-affe-6666fa72766d,Jennifer Martin,53,Oklahoma,90k+,Good,726,B
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,David Snyder,49,Hawaii,30k-60k,Very Good,764,A
...,...,...,...,...,...,...,...,...
995,baad3a54-d2c2-4533-8116-99f783761819,Michael Gregory,70,Washington,60k-90k,Very Good,758,B
996,2ce55216-dd6b-483a-9aec-ce201c8a3085,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A
997,a98d00e2-7d55-4459-b168-b9075a8d5640,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A
998,b198002d-13de-4f22-8b81-457e3807a733,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B
999,60c78083-2cfc-41c9-b880-cf086c8dfb1c,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B

In [14]:
customers['grade'].value_counts()

A    398
B    206
C    125
D     99
G     73
F     55
E     44
Name: grade, dtype: int64

In [15]:
loans = pd.merge(loan, customers, on = 'customer_id', how = 'left')

In [16]:
loans

,customer_id,loan_id,name,age,state,income_bracket,credit_score_band,score,grade
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,L1001,Christopher Miller,99,Maine,90k+,Very Good,778,A
1,101cd468-5a5c-4689-a4c3-8c4119613698,L1002,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,L1003,Michael Monroe,21,Rhode Island,<30k,Good,706,C
3,38c92c57-215c-48da-affe-6666fa72766d,L1004,Jennifer Martin,53,Oklahoma,90k+,Good,726,B
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,L1005,David Snyder,49,Hawaii,30k-60k,Very Good,764,A
...,...,...,...,...,...,...,...,...,...
1219,baad3a54-d2c2-4533-8116-99f783761819,L2220,Michael Gregory,70,Washington,60k-90k,Very Good,758,B
1220,2ce55216-dd6b-483a-9aec-ce201c8a3085,L2221,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A
1221,a98d00e2-7d55-4459-b168-b9075a8d5640,L2222,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A
1222,b198002d-13de-4f22-8b81-457e3807a733,L2223,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B
1223,60c78083-2cfc-41c9-b880-cf086c8dfb1c,L2224,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B

In [17]:
loans['term_months'] = 36
loans

,customer_id,loan_id,name,age,state,income_bracket,credit_score_band,score,grade,term_months
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,L1001,Christopher Miller,99,Maine,90k+,Very Good,778,A,36
1,101cd468-5a5c-4689-a4c3-8c4119613698,L1002,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A,36
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,L1003,Michael Monroe,21,Rhode Island,<30k,Good,706,C,36
3,38c92c57-215c-48da-affe-6666fa72766d,L1004,Jennifer Martin,53,Oklahoma,90k+,Good,726,B,36
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,L1005,David Snyder,49,Hawaii,30k-60k,Very Good,764,A,36
...,...,...,...,...,...,...,...,...,...,...
1219,baad3a54-d2c2-4533-8116-99f783761819,L2220,Michael Gregory,70,Washington,60k-90k,Very Good,758,B,36
1220,2ce55216-dd6b-483a-9aec-ce201c8a3085,L2221,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A,36
1221,a98d00e2-7d55-4459-b168-b9075a8d5640,L2222,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A,36
1222,b198002d-13de-4f22-8b81-457e3807a733,L2223,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B,36
1223,60c78083-2cfc-41c9-b880-cf086c8dfb1c,L2224,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B,36

In [21]:
start = datetime(2023,1,1)
end = datetime(2024,12,31)

loans['origination_date'] = pd.to_datetime(loans.apply(lambda x:fake.date_between_dates(date_start = start, date_end = end), axis = 1))
loans

,customer_id,loan_id,name,age,state,income_bracket,credit_score_band,score,grade,term_months,origination_date
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,L1001,Christopher Miller,99,Maine,90k+,Very Good,778,A,36,2023-05-03
1,101cd468-5a5c-4689-a4c3-8c4119613698,L1002,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A,36,2023-09-14
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,L1003,Michael Monroe,21,Rhode Island,<30k,Good,706,C,36,2024-09-26
3,38c92c57-215c-48da-affe-6666fa72766d,L1004,Jennifer Martin,53,Oklahoma,90k+,Good,726,B,36,2024-01-29
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,L1005,David Snyder,49,Hawaii,30k-60k,Very Good,764,A,36,2024-07-23
...,...,...,...,...,...,...,...,...,...,...,...
1219,baad3a54-d2c2-4533-8116-99f783761819,L2220,Michael Gregory,70,Washington,60k-90k,Very Good,758,B,36,2024-01-28
1220,2ce55216-dd6b-483a-9aec-ce201c8a3085,L2221,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A,36,2023-12-21
1221,a98d00e2-7d55-4459-b168-b9075a8d5640,L2222,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A,36,2024-02-20
1222,b198002d-13de-4f22-8b81-457e3807a733,L2223,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B,36,2024-02-25
1223,60c78083-2cfc-41c9-b880-cf086c8dfb1c,L2224,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B,36,2023-01-15

In [25]:
loans.dtypes

customer_id                  object
loan_id                      object
name                         object
age                           int64
state                        object
income_bracket               object
credit_score_band            object
score                         int64
grade                        object
term_months                   int64
origination_date     datetime64[ns]
apr                         float64
dtype: object

In [24]:
apr_dict = {'A':0.075,'B':0.105,'C':0.139,'D':0.178,'E':0.221,'F':0.262,'G':0.298}

loans['apr'] = loans.apply(lambda x: apr_dict[x['grade']], axis = 1)

loans

,customer_id,loan_id,name,age,state,income_bracket,credit_score_band,score,grade,term_months,origination_date,apr
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,L1001,Christopher Miller,99,Maine,90k+,Very Good,778,A,36,2023-05-03,0.075
1,101cd468-5a5c-4689-a4c3-8c4119613698,L1002,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A,36,2023-09-14,0.075
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,L1003,Michael Monroe,21,Rhode Island,<30k,Good,706,C,36,2024-09-26,0.139
3,38c92c57-215c-48da-affe-6666fa72766d,L1004,Jennifer Martin,53,Oklahoma,90k+,Good,726,B,36,2024-01-29,0.105
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,L1005,David Snyder,49,Hawaii,30k-60k,Very Good,764,A,36,2024-07-23,0.075
...,...,...,...,...,...,...,...,...,...,...,...,...
1219,baad3a54-d2c2-4533-8116-99f783761819,L2220,Michael Gregory,70,Washington,60k-90k,Very Good,758,B,36,2024-01-28,0.105
1220,2ce55216-dd6b-483a-9aec-ce201c8a3085,L2221,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A,36,2023-12-21,0.075
1221,a98d00e2-7d55-4459-b168-b9075a8d5640,L2222,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A,36,2024-02-20,0.075
1222,b198002d-13de-4f22-8b81-457e3807a733,L2223,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B,36,2024-02-25,0.105
1223,60c78083-2cfc-41c9-b880-cf086c8dfb1c,L2224,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B,36,2023-01-15,0.105

In [27]:
loans['loan_amount'] = loans.apply(lambda x: round(random.randint(1000,40000)/500)*500, axis = 1)
loans

,customer_id,loan_id,name,age,state,income_bracket,credit_score_band,score,grade,term_months,origination_date,apr,loan_amount
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,L1001,Christopher Miller,99,Maine,90k+,Very Good,778,A,36,2023-05-03,0.075,26000
1,101cd468-5a5c-4689-a4c3-8c4119613698,L1002,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A,36,2023-09-14,0.075,13500
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,L1003,Michael Monroe,21,Rhode Island,<30k,Good,706,C,36,2024-09-26,0.139,20500
3,38c92c57-215c-48da-affe-6666fa72766d,L1004,Jennifer Martin,53,Oklahoma,90k+,Good,726,B,36,2024-01-29,0.105,26500
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,L1005,David Snyder,49,Hawaii,30k-60k,Very Good,764,A,36,2024-07-23,0.075,8000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,baad3a54-d2c2-4533-8116-99f783761819,L2220,Michael Gregory,70,Washington,60k-90k,Very Good,758,B,36,2024-01-28,0.105,18000
1220,2ce55216-dd6b-483a-9aec-ce201c8a3085,L2221,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A,36,2023-12-21,0.075,6000
1221,a98d00e2-7d55-4459-b168-b9075a8d5640,L2222,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A,36,2024-02-20,0.075,7000
1222,b198002d-13de-4f22-8b81-457e3807a733,L2223,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B,36,2024-02-25,0.105,37500
1223,60c78083-2cfc-41c9-b880-cf086c8dfb1c,L2224,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B,36,2023-01-15,0.105,5000

In [28]:
(loans['loan_amount'] % 500 ==0).all()

True

In [32]:
loans['scheduled_payments'] = round(loans['loan_amount'] * (loans['apr']/12) / (1-(1+(loans['apr']/12))**(-loans['term_months'])),2)
loans

,customer_id,loan_id,name,age,state,income_bracket,credit_score_band,score,grade,term_months,origination_date,apr,loan_amount,sheduled_payments,scheduled_payments
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,L1001,Christopher Miller,99,Maine,90k+,Very Good,778,A,36,2023-05-03,0.075,26000,808.76,808.76
1,101cd468-5a5c-4689-a4c3-8c4119613698,L1002,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A,36,2023-09-14,0.075,13500,419.93,419.93
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,L1003,Michael Monroe,21,Rhode Island,<30k,Good,706,C,36,2024-09-26,0.139,20500,699.65,699.65
3,38c92c57-215c-48da-affe-6666fa72766d,L1004,Jennifer Martin,53,Oklahoma,90k+,Good,726,B,36,2024-01-29,0.105,26500,861.31,861.31
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,L1005,David Snyder,49,Hawaii,30k-60k,Very Good,764,A,36,2024-07-23,0.075,8000,248.85,248.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,baad3a54-d2c2-4533-8116-99f783761819,L2220,Michael Gregory,70,Washington,60k-90k,Very Good,758,B,36,2024-01-28,0.105,18000,585.04,585.04
1220,2ce55216-dd6b-483a-9aec-ce201c8a3085,L2221,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A,36,2023-12-21,0.075,6000,186.64,186.64
1221,a98d00e2-7d55-4459-b168-b9075a8d5640,L2222,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A,36,2024-02-20,0.075,7000,217.74,217.74
1222,b198002d-13de-4f22-8b81-457e3807a733,L2223,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B,36,2024-02-25,0.105,37500,1218.84,1218.84
1223,60c78083-2cfc-41c9-b880-cf086c8dfb1c,L2224,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B,36,2023-01-15,0.105,5000,162.51,162.51

In [33]:
loans['vintage_month'] = loans['origination_date'].dt.to_period('M').dt.to_timestamp()
loans

,customer_id,loan_id,name,age,state,income_bracket,credit_score_band,score,grade,term_months,origination_date,apr,loan_amount,sheduled_payments,scheduled_payments,vintage_month
0,c2a7af9e-ab79-4005-add1-77d2c700d84c,L1001,Christopher Miller,99,Maine,90k+,Very Good,778,A,36,2023-05-03,0.075,26000,808.76,808.76,2023-05-01
1,101cd468-5a5c-4689-a4c3-8c4119613698,L1002,Jason Nguyen,32,Texas,60k-90k,Excellent,805,A,36,2023-09-14,0.075,13500,419.93,419.93,2023-09-01
2,fa900d46-88e1-4883-aa6f-30c077c8cd55,L1003,Michael Monroe,21,Rhode Island,<30k,Good,706,C,36,2024-09-26,0.139,20500,699.65,699.65,2024-09-01
3,38c92c57-215c-48da-affe-6666fa72766d,L1004,Jennifer Martin,53,Oklahoma,90k+,Good,726,B,36,2024-01-29,0.105,26500,861.31,861.31,2024-01-01
4,ade19b1a-5d3e-438b-bd9e-f14dabd69cb9,L1005,David Snyder,49,Hawaii,30k-60k,Very Good,764,A,36,2024-07-23,0.075,8000,248.85,248.85,2024-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,baad3a54-d2c2-4533-8116-99f783761819,L2220,Michael Gregory,70,Washington,60k-90k,Very Good,758,B,36,2024-01-28,0.105,18000,585.04,585.04,2024-01-01
1220,2ce55216-dd6b-483a-9aec-ce201c8a3085,L2221,Stefanie Warren,29,West Virginia,90k+,Very Good,774,A,36,2023-12-21,0.075,6000,186.64,186.64,2023-12-01
1221,a98d00e2-7d55-4459-b168-b9075a8d5640,L2222,Melvin Pearson,46,Missouri,60k-90k,Very Good,784,A,36,2024-02-20,0.075,7000,217.74,217.74,2024-02-01
1222,b198002d-13de-4f22-8b81-457e3807a733,L2223,Nicole Meza,32,Rhode Island,30k-60k,Good,732,B,36,2024-02-25,0.105,37500,1218.84,1218.84,2024-02-01
1223,60c78083-2cfc-41c9-b880-cf086c8dfb1c,L2224,Nicole Rodriguez,77,Tennessee,60k-90k,Very Good,752,B,36,2023-01-15,0.105,5000,162.51,162.51,2023-01-01

In [34]:
loans.to_csv('/Users/aishwarya/Desktop/Projects/loan-portfolio-risk-analyzer/data/processed/loans.csv', index = False)